image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
  - test
  - deploy

test:
  stage: test
  allow_failure: false
  script:
    - cd AccuRanker.Tests
    - dotnet restore
    - dotnet test
 
deploy:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - cd AccuRanker
    - export VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' AccuRanker.csproj)
    - dotnet build --configuration=Release
    - dotnet pack --configuration=Release
    - dotnet nuget push bin/Release/DentsuDataLab.AccuRanker.$VERSION.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
